config/routes.rb
Rails.application.routes.draw do
  resources :votes

  resources :cities

  resources :parties

  resources :members

  get 'home/index'
  get 'nir' => "home#nir"
  get 'polymer_test' => "home#polymer_test"

  root 'home#index'

end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :members
  has_many :votes
  validates_uniqueness_of :name
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name, :lat, :lng)
    end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_form.html.haml
= form_for @city do |f|
  - if @city.errors.any?
    #error_explanation
      %h2= "#{pluralize(@city.errors.count, "error")} prohibited this city from being saved:"
      %ul
        - @city.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :lat
    = f.text_field :lat
  .field
    = f.label :lng
    = f.text_field :lng
  .actions
    = f.submit 'Save'

app/views/cities/edit.html.haml
%h1 Editing city

= render 'form'

= link_to 'Show', @city
\|
= link_to 'Back', cities_path

app/views/cities/index.html.haml
:javascript
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '760451830716871',
      xfbml      : true,
      version    : 'v2.2'
    });
  };

  (function(d, s, id){
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) {return;}
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

.social
  .fb-share-button{"data-href" => "https://developers.facebook.com/docs/plugins/", "data-layout" => "button_count"}
  .fb-like{"data-action" => "like", "data-href" => "https://developers.facebook.com/docs/plugins/", "data-layout" => "button_count", "data-share" => "false", "data-show-faces" => "true"}
   
%h1 Listing cities

%table
  %thead
    %tr
      %th Name
      %th Lat
      %th Lng
      %th
      %th
      %th
      
  %tbody
    - @cities.each do |city|
      %tr
        %td= city.name
        %td= city.lat
        %td= city.lng
        %td= link_to 'Show', city
        %td= link_to 'Edit', edit_city_path(city)
        %td= link_to 'Destroy', city, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New City', new_city_path
<paper-checkbox checked></paper-checkbox>

app/views/cities/new.html.haml
%h1 New city

= render 'form'

= link_to 'Back', cities_path

app/views/cities/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @city.name
%p
  %b Lat:
  = @city.lat
%p
  %b Lng:
  = @city.lng
%p
  %b Members:
  - @city.members.each do |member|
    = link_to member.name.titleize, member_url(member)

%p
  %b Members:
  %br
  - @city.votes.each do |vote|
    = link_to "#{vote.party.name}: #{vote.amount}", vote
    %br

= link_to 'Edit', edit_city_path(@city)
\|
= link_to 'Back', cities_path