config/routes.rb
Rails.application.routes.draw do
  resources :votes

  resources :cities

  resources :parties

  resources :members

  get 'home/index'
  get 'nir' => "home#nir"
  get 'polymer_test' => "home#polymer_test"

  root 'home#index'

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :city
  belongs_to :party
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_vote, only: [:show, :edit, :update, :destroy]

  # GET /votes
  # GET /votes.json
  def index
    @votes = Vote.paginate(:page => params[:page])
  end

  # GET /votes/1
  # GET /votes/1.json
  def show
  end

  # GET /votes/new
  def new
    @vote = Vote.new
  end

  # GET /votes/1/edit
  def edit
  end

  # POST /votes
  # POST /votes.json
  def create
    @vote = Vote.new(vote_params)

    respond_to do |format|
      if @vote.save
        format.html { redirect_to @vote, notice: 'Vote was successfully created.' }
        format.json { render :show, status: :created, location: @vote }
      else
        format.html { render :new }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /votes/1
  # PATCH/PUT /votes/1.json
  def update
    respond_to do |format|
      if @vote.update(vote_params)
        format.html { redirect_to @vote, notice: 'Vote was successfully updated.' }
        format.json { render :show, status: :ok, location: @vote }
      else
        format.html { render :edit }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votes/1
  # DELETE /votes/1.json
  def destroy
    @vote.destroy
    respond_to do |format|
      format.html { redirect_to votes_url, notice: 'Vote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vote
      @vote = Vote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vote_params
      params.require(:vote).permit(:amount, :city_id, :party_id)
    end
end

app/helpers/votes_helper.rb
module VotesHelper
  def party_link(vote)
    link_to vote.party.name, party_url(vote.party)
  end
  def city_link(vote)
    link_to vote.city.name, city_url(vote.city)
  end

end

app/views/votes/_form.html.haml
= form_for @vote do |f|
  - if @vote.errors.any?
    #error_explanation
      %h2= "#{pluralize(@vote.errors.count, "error")} prohibited this vote from being saved:"
      %ul
        - @vote.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :amount
    = f.number_field :amount
  .field
    = f.label :city_id
    = f.number_field :city_id
  .field
    = f.label :party_id
    = f.number_field :party_id
  .actions
    = f.submit 'Save'

app/views/votes/edit.html.haml
%h1 Editing vote

= render 'form'

= link_to 'Show', @vote
\|
= link_to 'Back', votes_path

app/views/votes/index.html.haml
%h1 Listing votes

%table
  %thead
    %tr
      %th Amount
      %th City
      %th Party
      %th
      %th
      %th
      
  %tbody
    - @votes.each do |vote|
      %tr
        %td= vote.amount
        %td= city_link(vote)
        %td= party_link(vote)
        %td= link_to 'Show', vote
        %td= link_to 'Edit', edit_vote_path(vote)
        %td= link_to 'Destroy', vote, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Vote', new_vote_path
= will_paginate @votes

app/views/votes/new.html.haml
%h1 New vote

= render 'form'

= link_to 'Back', votes_path

app/views/votes/show.html.haml
%p#notice= notice

%p
  %b Amount:
  = @vote.amount
%p
  %b City:
  = city_link(@vote)
%p
  %b Party:
  = party_link(@vote)

= link_to 'Edit', edit_vote_path(@vote)
\|
= link_to 'Back', votes_path