config/routes.rb
Rails.application.routes.draw do
  resources :votes

  resources :cities

  resources :parties

  resources :members

  get 'home/index'
  get 'nir' => "home#nir"
  get 'polymer_test' => "home#polymer_test"

  root 'home#index'

end

app/models/member.rb
class Member < ActiveRecord::Base
  validates_uniqueness_of :name
  belongs_to :city
  has_and_belongs_to_many :parties
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name)
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.haml
= form_for @member do |f|
  - if @member.errors.any?
    #error_explanation
      %h2= "#{pluralize(@member.errors.count, "error")} prohibited this member from being saved:"
      %ul
        - @member.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/members/edit.html.haml
%h1 Editing member

= render 'form'

= link_to 'Show', @member
\|
= link_to 'Back', members_path

app/views/members/index.html.haml
%h1 Listing members

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th
      
  %tbody
    - @members.each do |member|
      %tr
        %td= member.name
        %td= link_to 'Show', member
        %td= link_to 'Edit', edit_member_path(member)
        %td= link_to 'Destroy', member, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Member', new_member_path

app/views/members/new.html.haml
%h1 New member

= render 'form'

= link_to 'Back', members_path

app/views/members/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @member.name

%p
  %b Parties:
  - @member.parties.each do |party|
    = link_to party.name.titleize, party_url(party)
%p
  %b City:
  = link_to @member.city.name.titleize, city_url(@member.city)


= link_to 'Edit', edit_member_path(@member)
\|
= link_to 'Back', members_path